name: "Check documentation"

on:
    pull_request:
        branch:
            - devel

jobs:
    doc8:
        name: "Check doc8"
        runs-on: "ubuntu-latest"
        steps:
            - name: "Checkout"
              uses: "actions/checkout@v2"
            - name: doc8-check
              uses: deep-entertainment/doc8-action@v3
              with:
                ignorePaths: "_build,scripting/z_esc_reference.rst"
